source: src


# These values are overridden by GitHub Pages.
# They are repeated here to ensure local environments match.
safe: true
lsi: false
pygments: true


# Custom variables based on DPG. Set as needed for templates.
title: Flapjack Front-End
repo_name: front-end
repo_org: flapjack
# site_path: 
# prose_path: pages/CFPB/Prose/#
# home_link: /
# document_asset_path: /assets
